name: Cassbana CI
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    runs-on: ubuntu-latest
    name: Build and Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['27']      
        elixir: ['1.17.1']    

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: web/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        working-directory: web
        run: mix deps.get
      - name: Setup Test database
        working-directory: web
        run: mix ecto.create && mix ecto.migrate
        env:
          MIX_ENV: test
          MIX_DB_HOSTNAME: localhost
      - name: Run tests
        working-directory: web
        run: mix test
        env:
          MIX_ENV: test
          MIX_DB_HOSTNAME: localhost
